name: Run py-micp

on:
 push:
   branches:
     - main
 pull_request:
   
jobs:
  run-py-micp-local:
    permissions:
      contents: read
      pull-requests: write
    timeout-minutes: 10        
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        
    - name: Install python requirements
      run: |
        pip install -r requirements.txt
        pip install -r dev-requirements.txt
        
    - name: Check code style 
      run: |
        black --target-version py312 ./
        pylint ./ --ignore-paths="vpy-micp/","MRST","test_outputs"
        ruff check ./

    - name: Install GNU Octave
      run: |
        sudo apt-get update
        sudo apt-get install snapd
        sudo snap install octave
    
    - name: Download MRST
      run: |
        git clone https://github.com/SINTEF-AppliedCompSci/MRST.git
        pushd MRST
        git checkout 2026a
    
    - name: Install Flow Simulator
      run: |
        sudo apt-get update
        sudo apt-get install software-properties-common
        sudo apt-add-repository ppa:opm/ppa
        sudo apt-get update
        sudo apt-get install mpi-default-bin
        sudo apt-get install libopm-simulators-bin
      
    - name: Run the tests
      run: |
        pytest --basetemp=test_outputs --exitfirst tests/ --mrst_startup /home/runner/work/py-micp/py-micp/MRST/startup.m
